### ISSUE TITLE
Requiring Promise polyfill in this module bloats bundles

### ISSUE THREAD

**Issue by mshick** [gabrielflorit/typewriter-js#5]
I think it's a better idea to leave polyfills to he consuming builder / bundler. While you can easily add the polyfill externally, there is no easy way to get rid of it.

**Comment by gabrielflorit** [comment]
Good point.

**Comment by gabrielflorit** [comment]
I removed `Promise` and published `2.0.0`.

**Comment by mshick** [comment]
Nice, thanks!

**Comment by sobolevn** [comment]
What is the recommended way to do that? Is it possible to provide a link in the docs for that?

**Comment by gabrielflorit** [comment]
Is this https://github.com/gabrielflorit/typewriter-js#dependencies not sufficient?

**Comment by sobolevn** [comment]
Sorry, I missed it somehow. It is exactly what I needed.
